spring.application.name=game-service

fastapi.base-url=${FASTAPI_URL}
server.port=8082

spring.config.import=classpath:common-application.properties

core.service.url=${CORE_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.data.mongodb.uri=${MONGODB_URL}

server.forward-headers-strategy=native