version: '3.8'

services:
  # 1. Gateway Service
  gateway-service:
    image: ${DOCKER_REGISTRY}/gate-way-service:${IMAGE_TAG}
    container_name: gate-way-service
    restart: always
    ports:
      - "80:8080"  # HTTP
      - "8080:8080"
    env_file:
      - ./gateway.env

  # 2. Core Service
  core-service:
    image: ${DOCKER_REGISTRY}/core-service:${IMAGE_TAG}
    container_name: core-service
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - ./core.env

  # 3. Game Service
  game-service:
    image: ${DOCKER_REGISTRY}/game-service:${IMAGE_TAG}
    container_name: game-service
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - ./game.env
