spring.main.web-application-type=reactive

server.port=8080

# ??? ??
spring.application.name=gateway-service

# core-service ??? ??
spring.cloud.gateway.routes[0].id=core-service
#spring.cloud.gateway.routes[0].uri=http://core-service:8080
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/core/**

# game-service ??? ??
spring.cloud.gateway.routes[1].id=game-service
#spring.cloud.gateway.routes[1].uri=http://game-service:8080
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/game/**

spring.cloud.gateway.routes[2].id=game-service
#spring.cloud.gateway.routes[2].uri=http://game-service:8080
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/ws/**

spring.jwt.secret=${JWT_SECRET}

spring.cloud.compatibility-verifier.enabled=false

# ? Global CORS (????????)
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=https://tacticai.site
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# ? CORS ?? ?? ??(Allow-Origin, Allow-Credentials? ??)
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Expose-Headers RETAIN_FIRST

core.service.url=${CORE_URL}
game.service.url=${GAME_URL}
socket.service.url=${SOCKET_URL}

spring.codec.max-in-memory-size=500MB

server.forward-headers-strategy=native