spring.application.name=common-module

spring.jwt.secret=jKSHFKSajhf3298w76549w8efguhq4398thgfa4wq89th
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.password=

cloud.aws.s3.bucket=${S3_IMAGE_BUCKET}
cloud.aws.s3.bucket.game=${S3_GAME_BUCKET}
cloud.aws.stack.auto=false
cloud.aws.region.static=ap-northeast-2
cloud.aws.credentials.access-key=${S3_ACCESSKEY}
cloud.aws.credentials.secret-key=${S3_SECRETKEY}
