spring.application.name=common-module

spring.jwt.secret=${JWT_SERECT}
# Redis
spring.data.redis.host=${REDIS_URL}
spring.data.redis.port=${REDIS_USERNAME}
#spring.data.redis.password=${REDIS_PASSWORD}

cloud.aws.s3.bucket=${S3_IMAGE_BUCKET}
cloud.aws.stack.auto=false
cloud.aws.region.static=ap-northeast-2
cloud.aws.credentials.access-key=${S3_ACCESSKEY}
cloud.aws.credentials.secret-key=${S3_SECRETKEY}
