spring.application.name=core-service

server.port=8081

spring.config.import=classpath:common-application.properties

spring.profiles.front_url=http://localhost:3000

spring.datasource.url=jdbc:mysql://localhost:3306/tactical-ai-mysql
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
